#BDHM Assignment 2

#**Fixed length classification of peptides**

IMPORTING LIBRARIES

In [19]:
!pip install protlearn

In [20]:
pip install --upgrade protlearn

In [21]:

import pandas as pd
import numpy as np
import protlearn 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

LOADING TRAIN DATASET

In [22]:
print("Choose the Train data")

Choose the Train data


In [23]:

Train_data = input("Enter the path of train data:")



Enter the path of train data:/content/train BDMH(1).csv


In [24]:
Train=pd.read_csv(Train_data)

In [25]:
#Train=pd.read_csv('/content/train (2).csv')

In [26]:
Train


Sequence Label
0     SNIETVIECSISNIET     A
1     NGWTDTDSKGFEMIWD     A
2     THLKAVKMGVDVSMNT     A
3     HSKKKCDEVIKGGRHL     A
4     FRPKATDGAARCIDGA     A
...                ...   ...
6448  ADEVVRTKRYADEVVR     H
6449  IKILEDNKKIKILEDN     H
6450  ADSSNFYILQHADSSN     H
6451  IFTLVVIVCSLDIIAD     H
6452  EADIATMEVAEADIAT     H

[6453 rows x 2 columns]

REMOVING DUPLICATES FROM TRAIN DATASET

In [27]:
Train.drop_duplicates(subset ="Sequence",
                     keep = False, inplace = True)
Train

Sequence Label
0     SNIETVIECSISNIET     A
1     NGWTDTDSKGFEMIWD     A
2     THLKAVKMGVDVSMNT     A
3     HSKKKCDEVIKGGRHL     A
4     FRPKATDGAARCIDGA     A
...                ...   ...
6448  ADEVVRTKRYADEVVR     H
6449  IKILEDNKKIKILEDN     H
6450  ADSSNFYILQHADSSN     H
6451  IFTLVVIVCSLDIIAD     H
6452  EADIATMEVAEADIAT     H

[6364 rows x 2 columns]

In [28]:
#converting it to an array
Train  = np.array(Train)
Train

array([['SNIETVIECSISNIET', 'A'],
       ['NGWTDTDSKGFEMIWD', 'A'],
       ['THLKAVKMGVDVSMNT', 'A'],
       ...,
       ['ADSSNFYILQHADSSN', 'H'],
       ['IFTLVVIVCSLDIIAD', 'H'],
       ['EADIATMEVAEADIAT', 'H']], dtype=object)

In [29]:
#making a list of sequence as required by the protlearn package
Sequence = []
for i in range (6364):
  Sequence.append(Train[i][0])
Sequence  


['SNIETVIECSISNIET',
 'NGWTDTDSKGFEMIWD',
 'THLKAVKMGVDVSMNT',
 'HSKKKCDEVIKGGRHL',
 'FRPKATDGAARCIDGA',
 'PEEEGGRLRLDAITGP',
 'YAQAYPNVWNEKYAQA',
 'AQDQEPDAPAHAYGYA',
 'LKLATGMRCPRYVKQN',
 'LPEIVHSSMLQYAGFL',
 'IVGAYGAAGGSISYEY',
 'DVSASMHWKRTLLSLD',
 'KGVSPTGNLTREMPAW',
 'IAKRPKVRHYSSRRFT',
 'GDPGLAYGWRGFYIAG',
 'VVALGSQEPHATKQSV',
 'AGWILGNPPLQLGNCS',
 'HLCGSHLVPAAAFVNQ',
 'CPTDCFRKVGNNTLIC',
 'EYRAVTELYVRFDSDV',
 'AYDEEARRKTIAYDEE',
 'QLCCQQLWTYQLVQQL',
 'GRLTWRKMGDMLLLWG',
 'KCGSGPWLHPEATYTK',
 'DYASFSRASTDDYASF',
 'KVFLENVIEETRGVLK',
 'GPPGTGKSQKYSTLQG',
 'VTTVKVPMEEDFHVDQ',
 'QQEAIKSAGEQQEAIK',
 'PLLANNRETLTKTLVL',
 'PCPIIHNLCNTNWLPP',
 'NSENGICYIVETPNSE',
 'AIRPKVRDKKFKPEIA',
 'FKGEQGPKGFKGEQGP',
 'DPNANPNVDPNANPNV',
 'NGITNKVNDQKSTQNA',
 'EGSLQKRGIAGSLQPL',
 'RSRPSTAHRSSRHPRR',
 'CAKFTCAKGKGSIVAC',
 'LGEYGEVTAPSYTLKL',
 'AGTPADTGCSKAFKFA',
 'AGQSIVFGFVGYHGTF',
 'AAILTQQAMAEMITEA',
 'VDGWYGYHGFIEGGWT',
 'RVYVPRSAIRNGALLR',
 'MFSALSEGPEVIPMFS',
 'RVYVPRSSIRNGAALR',
 'LCAGPGASLPG

Removing sequence contining unnatural amino acid using protlearn

In [30]:
from protlearn.preprocessing import remove_unnatural

In [31]:
Sequence=protlearn.preprocessing.remove_unnatural(Sequence)

In [32]:
Sequence

['SNIETVIECSISNIET',
 'NGWTDTDSKGFEMIWD',
 'THLKAVKMGVDVSMNT',
 'HSKKKCDEVIKGGRHL',
 'FRPKATDGAARCIDGA',
 'PEEEGGRLRLDAITGP',
 'YAQAYPNVWNEKYAQA',
 'AQDQEPDAPAHAYGYA',
 'LKLATGMRCPRYVKQN',
 'LPEIVHSSMLQYAGFL',
 'IVGAYGAAGGSISYEY',
 'DVSASMHWKRTLLSLD',
 'KGVSPTGNLTREMPAW',
 'IAKRPKVRHYSSRRFT',
 'GDPGLAYGWRGFYIAG',
 'VVALGSQEPHATKQSV',
 'AGWILGNPPLQLGNCS',
 'HLCGSHLVPAAAFVNQ',
 'CPTDCFRKVGNNTLIC',
 'EYRAVTELYVRFDSDV',
 'AYDEEARRKTIAYDEE',
 'QLCCQQLWTYQLVQQL',
 'GRLTWRKMGDMLLLWG',
 'KCGSGPWLHPEATYTK',
 'DYASFSRASTDDYASF',
 'KVFLENVIEETRGVLK',
 'GPPGTGKSQKYSTLQG',
 'VTTVKVPMEEDFHVDQ',
 'QQEAIKSAGEQQEAIK',
 'PLLANNRETLTKTLVL',
 'PCPIIHNLCNTNWLPP',
 'NSENGICYIVETPNSE',
 'AIRPKVRDKKFKPEIA',
 'FKGEQGPKGFKGEQGP',
 'DPNANPNVDPNANPNV',
 'NGITNKVNDQKSTQNA',
 'EGSLQKRGIAGSLQPL',
 'RSRPSTAHRSSRHPRR',
 'CAKFTCAKGKGSIVAC',
 'LGEYGEVTAPSYTLKL',
 'AGTPADTGCSKAFKFA',
 'AGQSIVFGFVGYHGTF',
 'AAILTQQAMAEMITEA',
 'VDGWYGYHGFIEGGWT',
 'RVYVPRSAIRNGALLR',
 'MFSALSEGPEVIPMFS',
 'RVYVPRSSIRNGAALR',
 'LCAGPGASLPG

#Feature Exatraction from Train Dataset

Extracting Amino acid composition feature using protlearn

In [33]:
from protlearn.features import aac

In [34]:
comp, aa = aac(Sequence, remove_zero_cols=True)
comp

array([[0.    , 0.0625, 0.    , ..., 0.0625, 0.    , 0.    ],
       [0.    , 0.    , 0.1875, ..., 0.    , 0.125 , 0.    ],
       [0.0625, 0.    , 0.0625, ..., 0.1875, 0.    , 0.    ],
       ...,
       [0.125 , 0.    , 0.125 , ..., 0.    , 0.    , 0.0625],
       [0.0625, 0.0625, 0.125 , ..., 0.1875, 0.    , 0.    ],
       [0.3125, 0.    , 0.125 , ..., 0.0625, 0.    , 0.    ]])

In [35]:
comp=pd.DataFrame(comp) #converting array to dataframe
comp

0       1       2       3       4       5       6       7       8   \
0     0.0000  0.0625  0.0000  0.1875  0.0000  0.0000  0.0000  0.2500  0.0000   
1     0.0000  0.0000  0.1875  0.0625  0.0625  0.1250  0.0000  0.0625  0.0625   
2     0.0625  0.0000  0.0625  0.0000  0.0000  0.0625  0.0625  0.0000  0.1250   
3     0.0000  0.0625  0.0625  0.0625  0.0000  0.1250  0.1250  0.0625  0.2500   
4     0.2500  0.0625  0.1250  0.0000  0.0625  0.1250  0.0000  0.0625  0.0625   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6359  0.1250  0.0000  0.1250  0.1250  0.0000  0.0000  0.0000  0.0000  0.0625   
6360  0.0000  0.0000  0.1250  0.1250  0.0000  0.0000  0.0000  0.2500  0.2500   
6361  0.1250  0.0000  0.1250  0.0000  0.0625  0.0000  0.0625  0.0625  0.0000   
6362  0.0625  0.0625  0.1250  0.0000  0.0625  0.0000  0.0000  0.2500  0.0000   
6363  0.3125  0.0000  0.1250  0.1875  0.0000  0.0000  0.0000  0.1250  0.0000   

          9       10      11      12      13      14      15      16      17  \
0     0.0000  0.0000  0.1250  0.0000  0.0000  0.0000  0.1875  0.1250  0.0625   
1     0.0000  0.0625  0.0625  0.0000  0.0000  0.0000  0.0625  0.1250  0.0000   
2     0.0625  0.1250  0.0625  0.0000  0.0000  0.0000  0.0625  0.1250  0.1875   
3     0.0625  0.0000  0.0000  0.0000  0.0000  0.0625  0.0625  0.0000  0.0625   
4     0.0000  0.0000  0.0000  0.0625  0.0000  0.1250  0.0000  0.0625  0.0000   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6359  0.0000  0.0000  0.0000  0.0000  0.0000  0.1875  0.0000  0.0625  0.2500   
6360  0.1250  0.0000  0.1250  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
6361  0.0625  0.0000  0.1250  0.0000  0.0625  0.0000  0.2500  0.0000  0.0000   
6362  0.1250  0.0000  0.0000  0.0000  0.0000  0.0000  0.0625  0.0625  0.1875   
6363  0.0000  0.0625  0.0000  0.0000  0.0000  0.0000  0.0000  0.1250  0.0625   

         18      19  
0     0.000  0.0000  
1     0.125  0.0000  
2     0.000  0.0000  
3     0.000  0.0000  
4     0.000  0.0000  
...     ...     ...  
6359  0.000  0.0625  
6360  0.000  0.0000  
6361  0.000  0.0625  
6362  0.000  0.0000  
6363  0.000  0.0000  

[6364 rows x 20 columns]

Exatracting dipeptide amino acid composition from sequence of  Train dataset

In [36]:
from protlearn.features import ngram
di, ngrams = ngram(Sequence, n=2)
di

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.13333333, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.06666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.13333333, ..., 0.        , 0.        ,
        0.        ]])

In [37]:
di=pd.DataFrame(di)
di

0    1         2         3    4    5    6    7    8    9    ...  \
0     0.000000  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
1     0.000000  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
2     0.000000  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
3     0.000000  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
4     0.066667  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
...        ...  ...       ...       ...  ...  ...  ...  ...  ...  ...  ...   
6359  0.000000  0.0  0.133333  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
6360  0.000000  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
6361  0.000000  0.0  0.133333  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
6362  0.000000  0.0  0.066667  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  ...   
6363  0.000000  0.0  0.133333  0.066667  0.0  0.0  0.0  0.0  0.0  0.0  ...   

      390  391  392  393  394  395  396  397  398  399  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
6359  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6360  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6361  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6362  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6363  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[6364 rows x 400 columns]

Exatracting Tripeptide amino acid composition from sequence of  Train dataset

In [38]:
tri, ngrams = ngram(Sequence, n=3)

In [39]:
tri

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [40]:
tri=pd.DataFrame(tri)
tri

0     1     2     3     4     5     6     7     8     9     ...  7990  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
6359   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6360   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6361   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6362   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6363   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      7991  7992  7993  7994  7995  7996  7997  7998  7999  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
6359   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6360   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6361   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6362   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6363   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[6364 rows x 8000 columns]

Exatracting binary profile pattern for each amino acid sequence in the dataset. 

In [41]:
from protlearn.features import binary
bpp = binary(Sequence, padding=True)
bpp

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
bpp=pd.DataFrame(bpp)

In [43]:
bpp

0    1    2    3    4    5    6    7    8    9    ...  310  311  312  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
6359  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6360  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  0.0   
6361  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
6362  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
6363  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      313  314  315  316  317  318  319  
0     0.0  0.0  0.0  1.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
6359  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
6360  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6361  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6362  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6363  0.0  0.0  0.0  1.0  0.0  0.0  0.0  

[6364 rows x 320 columns]

Concatinating all the features in pne dataframe which is our X Train

In [44]:
X_Train=pd.concat((comp,di,tri), axis=1)

In [45]:
X_Train

0       1       2       3       4       5       6       7       8     \
0     0.0000  0.0625  0.0000  0.1875  0.0000  0.0000  0.0000  0.2500  0.0000   
1     0.0000  0.0000  0.1875  0.0625  0.0625  0.1250  0.0000  0.0625  0.0625   
2     0.0625  0.0000  0.0625  0.0000  0.0000  0.0625  0.0625  0.0000  0.1250   
3     0.0000  0.0625  0.0625  0.0625  0.0000  0.1250  0.1250  0.0625  0.2500   
4     0.2500  0.0625  0.1250  0.0000  0.0625  0.1250  0.0000  0.0625  0.0625   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6359  0.1250  0.0000  0.1250  0.1250  0.0000  0.0000  0.0000  0.0000  0.0625   
6360  0.0000  0.0000  0.1250  0.1250  0.0000  0.0000  0.0000  0.2500  0.2500   
6361  0.1250  0.0000  0.1250  0.0000  0.0625  0.0000  0.0625  0.0625  0.0000   
6362  0.0625  0.0625  0.1250  0.0000  0.0625  0.0000  0.0000  0.2500  0.0000   
6363  0.3125  0.0000  0.1250  0.1875  0.0000  0.0000  0.0000  0.1250  0.0000   

        9     ...  7990  7991  7992  7993  7994  7995  7996  7997  7998  7999  
0     0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...      ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
6359  0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6360  0.1250  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6361  0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6362  0.1250  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6363  0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[6364 rows x 8420 columns]

Getting the Train labels

In [46]:
Train=pd.DataFrame(Train)

In [47]:
Train

0  1
0     SNIETVIECSISNIET  A
1     NGWTDTDSKGFEMIWD  A
2     THLKAVKMGVDVSMNT  A
3     HSKKKCDEVIKGGRHL  A
4     FRPKATDGAARCIDGA  A
...                ... ..
6359  ADEVVRTKRYADEVVR  H
6360  IKILEDNKKIKILEDN  H
6361  ADSSNFYILQHADSSN  H
6362  IFTLVVIVCSLDIIAD  H
6363  EADIATMEVAEADIAT  H

[6364 rows x 2 columns]

In [48]:
Y_Train=Train[1]

In [49]:
Y_Train #labels of train dataset

0       A
1       A
2       A
3       A
4       A
       ..
6359    H
6360    H
6361    H
6362    H
6363    H
Name: 1, Length: 6364, dtype: object

#Importing Test dataset

In [50]:
print("Choose test data:")

Choose test data:


In [51]:
Test_data = input("Enter the path of test data:")

Enter the path of test data:/content/test BDMH(1).csv


In [52]:
#Test=pd.read_csv('/content/test (4).csv')

In [53]:
Test=pd.read_csv(Test_data)


In [54]:
Test

ID          Sequence
0     1001  AAAIARAGLRHAGGVA
1     1002  AAATGFVKSIAAATGF
2     1003  AADKVEKVDWRTLYIA
3     1004  AADQDPSCLTIQIESA
4     1005  AAEKTKQGAKEGVVAA
...    ...               ...
1611  2612  YYCPLTEEAPPYYCPL
1612  2613  YYFYQQIYPRHGEQFY
1613  2614  YYILCYARHNAPFLYY
1614  2615  YYKAFKITYCKGLDIY
1615  2616  YYWHTGYISLTGKKYT

[1616 rows x 2 columns]

In [55]:
print("Wait model is loading...")

Wait model is loading...


In [56]:
Test=pd.DataFrame(Test)

In [57]:
#converting it to an array
Test  = np.array(Test)
Test

array([[1001, 'AAAIARAGLRHAGGVA'],
       [1002, 'AAATGFVKSIAAATGF'],
       [1003, 'AADKVEKVDWRTLYIA'],
       ...,
       [2614, 'YYILCYARHNAPFLYY'],
       [2615, 'YYKAFKITYCKGLDIY'],
       [2616, 'YYWHTGYISLTGKKYT']], dtype=object)

In [58]:
#making a list of sequence as required by the protlearn package
sequence = []
for i in range (1616):
  sequence.append(Test[i][1])
sequence  


['AAAIARAGLRHAGGVA',
 'AAATGFVKSIAAATGF',
 'AADKVEKVDWRTLYIA',
 'AADQDPSCLTIQIESA',
 'AAEKTKQGAKEGVVAA',
 'AAFNDAIKDKFTVFEA',
 'AAGVYAVDDFVRAAGV',
 'AALGVLMSGSLIYSTA',
 'AANAAPANAFKVAATA',
 'AANAPPADDVNAGFKA',
 'AAQSIVFGFVGAHGTF',
 'AAQSIVFGFVGYAGTF',
 'AAQSIVFGFVGYHGTF',
 'AARSLGQPNPSIGLFG',
 'AATAPADDFKVAATAA',
 'AATIRKVQRGGWSYYA',
 'AATLAQEAMAEMKTDA',
 'AAVLAALGIGVDSRTR',
 'AAVPSGASTSKGLFRA',
 'ACEAKKKAIVACVKAA',
 'ACLLHNKYKCHLTNIA',
 'ADPRGTRSTAYLYGIA',
 'ADTAYESKVIPEGWKA',
 'ADTPANCTCCWRQIIA',
 'ADTSYESKVIPEGWKA',
 'ADTSYSAKSEFEDVIP',
 'AEELFTFGQEIYMQHT',
 'AEINEAGRAEINEAGR',
 'AERRFQAPQFLGVPYA',
 'AESVRDHLEPAYFATA',
 'AEVGSSRSRSSWCTAE',
 'AFPSKTSAIYFNTWTT',
 'AFSREVLEGPGGENPE',
 'AFSWEVLEGAGGEDPE',
 'AFTEIKVQRMAFTEIK',
 'AGALNKATLKHGGGVA',
 'AGDLYSRRIRHAILAA',
 'AGGHNAVFFQDAYNAA',
 'AGGHNAVFFQDAYNGA',
 'AGLAAAAPIASLFAAA',
 'AGNVQLRVNHNFLVQA',
 'AGSEGTGQLWKGFSFI',
 'AGSGIIISAFAMERNA',
 'AGTIRSEVPFTPTQKR',
 'AGTPEVHASEALRIIA',
 'AGVVAVEVYSDLYQLA',
 'AHAEINEAISQAVHAA',
 'AHAGDMAGMSQ

Removing sequence contining unnatural amino acid using protlearn

In [59]:
from protlearn.preprocessing import remove_unnatural

In [60]:
sequence=protlearn.preprocessing.remove_unnatural(sequence)

In [61]:
sequence

['AAAIARAGLRHAGGVA',
 'AAATGFVKSIAAATGF',
 'AADKVEKVDWRTLYIA',
 'AADQDPSCLTIQIESA',
 'AAEKTKQGAKEGVVAA',
 'AAFNDAIKDKFTVFEA',
 'AAGVYAVDDFVRAAGV',
 'AALGVLMSGSLIYSTA',
 'AANAAPANAFKVAATA',
 'AANAPPADDVNAGFKA',
 'AAQSIVFGFVGAHGTF',
 'AAQSIVFGFVGYAGTF',
 'AAQSIVFGFVGYHGTF',
 'AARSLGQPNPSIGLFG',
 'AATAPADDFKVAATAA',
 'AATIRKVQRGGWSYYA',
 'AATLAQEAMAEMKTDA',
 'AAVLAALGIGVDSRTR',
 'AAVPSGASTSKGLFRA',
 'ACEAKKKAIVACVKAA',
 'ACLLHNKYKCHLTNIA',
 'ADPRGTRSTAYLYGIA',
 'ADTAYESKVIPEGWKA',
 'ADTPANCTCCWRQIIA',
 'ADTSYESKVIPEGWKA',
 'ADTSYSAKSEFEDVIP',
 'AEELFTFGQEIYMQHT',
 'AEINEAGRAEINEAGR',
 'AERRFQAPQFLGVPYA',
 'AESVRDHLEPAYFATA',
 'AEVGSSRSRSSWCTAE',
 'AFPSKTSAIYFNTWTT',
 'AFSREVLEGPGGENPE',
 'AFSWEVLEGAGGEDPE',
 'AFTEIKVQRMAFTEIK',
 'AGALNKATLKHGGGVA',
 'AGDLYSRRIRHAILAA',
 'AGGHNAVFFQDAYNAA',
 'AGGHNAVFFQDAYNGA',
 'AGLAAAAPIASLFAAA',
 'AGNVQLRVNHNFLVQA',
 'AGSEGTGQLWKGFSFI',
 'AGSGIIISAFAMERNA',
 'AGTIRSEVPFTPTQKR',
 'AGTPEVHASEALRIIA',
 'AGVVAVEVYSDLYQLA',
 'AHAEINEAISQAVHAA',
 'AHAGDMAGMSQ

#Feature Exatraction from Test Dataset

Extracting Amino acid composition feature using protlearn

In [62]:
from protlearn.features import aac

In [63]:
Comp, AA = aac(sequence, remove_zero_cols=True)
Comp

array([[0.4375, 0.    , 0.    , ..., 0.0625, 0.    , 0.    ],
       [0.375 , 0.    , 0.    , ..., 0.0625, 0.    , 0.    ],
       [0.1875, 0.    , 0.125 , ..., 0.125 , 0.0625, 0.0625],
       ...,
       [0.125 , 0.0625, 0.    , ..., 0.    , 0.    , 0.3125],
       [0.0625, 0.0625, 0.0625, ..., 0.    , 0.    , 0.25  ],
       [0.    , 0.    , 0.    , ..., 0.    , 0.0625, 0.25  ]])

In [64]:
Comp=pd.DataFrame(Comp)
Comp

0       1       2       3       4       5       6       7       8   \
0     0.4375  0.0000  0.0000  0.0000  0.0000  0.1875  0.0625  0.0625  0.0000   
1     0.3750  0.0000  0.0000  0.0000  0.1250  0.1250  0.0000  0.0625  0.0625   
2     0.1875  0.0000  0.1250  0.0625  0.0000  0.0000  0.0000  0.0625  0.1250   
3     0.1875  0.0625  0.1250  0.0625  0.0000  0.0000  0.0000  0.1250  0.0000   
4     0.3125  0.0000  0.0000  0.1250  0.0000  0.1250  0.0000  0.0000  0.1875   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1611  0.0625  0.1250  0.0000  0.1250  0.0000  0.0000  0.0000  0.0000  0.0000   
1612  0.0000  0.0000  0.0000  0.0625  0.1250  0.0625  0.0625  0.0625  0.0000   
1613  0.1250  0.0625  0.0000  0.0000  0.0625  0.0000  0.0625  0.0625  0.0000   
1614  0.0625  0.0625  0.0625  0.0000  0.0625  0.0625  0.0000  0.1250  0.1875   
1615  0.0000  0.0000  0.0000  0.0000  0.0000  0.1250  0.0625  0.0625  0.1250   

          9    10      11      12      13      14      15      16      17  \
0     0.0625  0.0  0.0000  0.0000  0.0000  0.1250  0.0000  0.0000  0.0625   
1     0.0000  0.0  0.0000  0.0000  0.0000  0.0000  0.0625  0.1250  0.0625   
2     0.0625  0.0  0.0000  0.0000  0.0000  0.0625  0.0000  0.0625  0.1250   
3     0.0625  0.0  0.0000  0.0625  0.1250  0.0000  0.1250  0.0625  0.0000   
4     0.0000  0.0  0.0000  0.0000  0.0625  0.0000  0.0000  0.0625  0.1250   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
1611  0.1250  0.0  0.0000  0.2500  0.0000  0.0000  0.0000  0.0625  0.0000   
1612  0.0000  0.0  0.0000  0.0625  0.1875  0.0625  0.0000  0.0000  0.0000   
1613  0.1250  0.0  0.0625  0.0625  0.0000  0.0625  0.0000  0.0000  0.0000   
1614  0.0625  0.0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0625  0.0000   
1615  0.0625  0.0  0.0000  0.0000  0.0000  0.0000  0.0625  0.1875  0.0000   

          18      19  
0     0.0000  0.0000  
1     0.0000  0.0000  
2     0.0625  0.0625  
3     0.0000  0.0000  
4     0.0000  0.0000  
...      ...     ...  
1611  0.0000  0.2500  
1612  0.0000  0.3125  
1613  0.0000  0.3125  
1614  0.0000  0.2500  
1615  0.0625  0.2500  

[1616 rows x 20 columns]

Exatracting dipeptide amino acid composition from sequence of  Test dataset

In [65]:
from protlearn.features import ngram
Di, Ngrams = ngram(sequence, n=2)
Di

array([[0.13333333, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.26666667, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.06666667, 0.        , 0.06666667, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.13333333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.06666667],
       [0.        , 0.        , 0.        , ..., 0.        , 0.06666667,
        0.06666667]])

In [66]:
Di=pd.DataFrame(Di)
Di

0    1         2         3         4         5    6         7    \
0     0.133333  0.0  0.000000  0.000000  0.000000  0.133333  0.0  0.066667   
1     0.266667  0.0  0.000000  0.000000  0.000000  0.000000  0.0  0.000000   
2     0.066667  0.0  0.066667  0.000000  0.000000  0.000000  0.0  0.000000   
3     0.066667  0.0  0.066667  0.000000  0.000000  0.000000  0.0  0.000000   
4     0.133333  0.0  0.000000  0.066667  0.000000  0.000000  0.0  0.000000   
...        ...  ...       ...       ...       ...       ...  ...       ...   
1611  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.0  0.000000   
1612  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.0  0.000000   
1613  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.0  0.000000   
1614  0.000000  0.0  0.000000  0.000000  0.066667  0.000000  0.0  0.000000   
1615  0.000000  0.0  0.000000  0.000000  0.000000  0.000000  0.0  0.000000   

           8    9    ...  390  391       392       393  394  395       396  \
0     0.000000  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.000000   
1     0.000000  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.000000   
2     0.000000  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.000000   
3     0.000000  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.000000   
4     0.066667  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.000000   
...        ...  ...  ...  ...  ...       ...       ...  ...  ...       ...   
1611  0.000000  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.000000   
1612  0.000000  0.0  ...  0.0  0.0  0.066667  0.066667  0.0  0.0  0.000000   
1613  0.000000  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.000000   
1614  0.000000  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.000000   
1615  0.000000  0.0  ...  0.0  0.0  0.000000  0.000000  0.0  0.0  0.066667   

      397       398       399  
0     0.0  0.000000  0.000000  
1     0.0  0.000000  0.000000  
2     0.0  0.000000  0.000000  
3     0.0  0.000000  0.000000  
4     0.0  0.000000  0.000000  
...   ...       ...       ...  
1611  0.0  0.000000  0.133333  
1612  0.0  0.000000  0.066667  
1613  0.0  0.000000  0.133333  
1614  0.0  0.000000  0.066667  
1615  0.0  0.066667  0.066667  

[1616 rows x 400 columns]

Exatracting Tripeptide amino acid composition from sequence of  Test dataset

In [67]:
Tri, Ngrams = ngram(sequence, n=3)
Tri

array([[0.07142857, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.14285714, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.07142857, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.07142857,
        0.        ]])

In [68]:
Tri=pd.DataFrame(Tri)
Tri

0     1         2         3     4     5     6         7     8     \
0     0.071429   0.0  0.000000  0.000000   0.0   0.0   0.0  0.071429   0.0   
1     0.142857   0.0  0.000000  0.000000   0.0   0.0   0.0  0.000000   0.0   
2     0.000000   0.0  0.071429  0.000000   0.0   0.0   0.0  0.000000   0.0   
3     0.000000   0.0  0.071429  0.000000   0.0   0.0   0.0  0.000000   0.0   
4     0.000000   0.0  0.000000  0.071429   0.0   0.0   0.0  0.000000   0.0   
...        ...   ...       ...       ...   ...   ...   ...       ...   ...   
1611  0.000000   0.0  0.000000  0.000000   0.0   0.0   0.0  0.000000   0.0   
1612  0.000000   0.0  0.000000  0.000000   0.0   0.0   0.0  0.000000   0.0   
1613  0.000000   0.0  0.000000  0.000000   0.0   0.0   0.0  0.000000   0.0   
1614  0.000000   0.0  0.000000  0.000000   0.0   0.0   0.0  0.000000   0.0   
1615  0.000000   0.0  0.000000  0.000000   0.0   0.0   0.0  0.000000   0.0   

      9     ...  7990  7991  7992  7993  7994  7995  7996  7997      7998  \
0      0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1      0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
2      0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
3      0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
4      0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
...    ...  ...   ...   ...   ...   ...   ...   ...   ...   ...       ...   
1611   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1612   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1613   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1614   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1615   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.071429   

      7999  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
1611   0.0  
1612   0.0  
1613   0.0  
1614   0.0  
1615   0.0  

[1616 rows x 8000 columns]

Exatracting binary profile pattern for each amino acid sequence in the dataset. 

In [69]:
from protlearn.features import binary
Bpp = binary(sequence, padding=True)
Bpp

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [70]:
Bpp=pd.DataFrame(Bpp)

In [71]:
Bpp

0    1    2    3    4    5    6    7    8    9    ...  310  311  312  \
0     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1611  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1612  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1613  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1614  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1615  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      313  314  315  316  317  318  319  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
1611  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1612  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
1613  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
1614  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
1615  0.0  0.0  0.0  1.0  0.0  0.0  0.0  

[1616 rows x 320 columns]

**Feature Selection**

Concatinating all the features in pne dataframe which is our X Train

In [72]:
X_Test=pd.concat((Comp,Di,Tri), axis=1)
X_Test

0       1       2       3       4       5       6       7       8     \
0     0.4375  0.0000  0.0000  0.0000  0.0000  0.1875  0.0625  0.0625  0.0000   
1     0.3750  0.0000  0.0000  0.0000  0.1250  0.1250  0.0000  0.0625  0.0625   
2     0.1875  0.0000  0.1250  0.0625  0.0000  0.0000  0.0000  0.0625  0.1250   
3     0.1875  0.0625  0.1250  0.0625  0.0000  0.0000  0.0000  0.1250  0.0000   
4     0.3125  0.0000  0.0000  0.1250  0.0000  0.1250  0.0000  0.0000  0.1875   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1611  0.0625  0.1250  0.0000  0.1250  0.0000  0.0000  0.0000  0.0000  0.0000   
1612  0.0000  0.0000  0.0000  0.0625  0.1250  0.0625  0.0625  0.0625  0.0000   
1613  0.1250  0.0625  0.0000  0.0000  0.0625  0.0000  0.0625  0.0625  0.0000   
1614  0.0625  0.0625  0.0625  0.0000  0.0625  0.0625  0.0000  0.1250  0.1875   
1615  0.0000  0.0000  0.0000  0.0000  0.0000  0.1250  0.0625  0.0625  0.1250   

        9     ...  7990  7991  7992  7993  7994  7995  7996  7997      7998  \
0     0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1     0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
2     0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
3     0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
4     0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
...      ...  ...   ...   ...   ...   ...   ...   ...   ...   ...       ...   
1611  0.1250  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1612  0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1613  0.1250  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1614  0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.000000   
1615  0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.071429   

      7999  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
1611   0.0  
1612   0.0  
1613   0.0  
1614   0.0  
1615   0.0  

[1616 rows x 8420 columns]

In [73]:
X_Train

0       1       2       3       4       5       6       7       8     \
0     0.0000  0.0625  0.0000  0.1875  0.0000  0.0000  0.0000  0.2500  0.0000   
1     0.0000  0.0000  0.1875  0.0625  0.0625  0.1250  0.0000  0.0625  0.0625   
2     0.0625  0.0000  0.0625  0.0000  0.0000  0.0625  0.0625  0.0000  0.1250   
3     0.0000  0.0625  0.0625  0.0625  0.0000  0.1250  0.1250  0.0625  0.2500   
4     0.2500  0.0625  0.1250  0.0000  0.0625  0.1250  0.0000  0.0625  0.0625   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6359  0.1250  0.0000  0.1250  0.1250  0.0000  0.0000  0.0000  0.0000  0.0625   
6360  0.0000  0.0000  0.1250  0.1250  0.0000  0.0000  0.0000  0.2500  0.2500   
6361  0.1250  0.0000  0.1250  0.0000  0.0625  0.0000  0.0625  0.0625  0.0000   
6362  0.0625  0.0625  0.1250  0.0000  0.0625  0.0000  0.0000  0.2500  0.0000   
6363  0.3125  0.0000  0.1250  0.1875  0.0000  0.0000  0.0000  0.1250  0.0000   

        9     ...  7990  7991  7992  7993  7994  7995  7996  7997  7998  7999  
0     0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...      ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
6359  0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6360  0.1250  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6361  0.0625  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6362  0.1250  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
6363  0.0000  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[6364 rows x 8420 columns]

**Principal component analysis.**

In [ ]:
from protlearn.dimreduction import pca
rrrrreduced = pca(X_Train, thres=.9)
rrrrreduced

In [ ]:
from protlearn.dimreduction import pca
RRRRReduced = pca(X_Test, thres=.9)
RRRRReduced

*Normalizing X train and X test (Features)*

In [74]:
from sklearn import preprocessing

In [75]:
X_Train = preprocessing.normalize(X_Train)
X_Train

array([[0.        , 0.09958142, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.37031975, ..., 0.        , 0.        ,
        0.        ],
       [0.12563728, 0.        , 0.12563728, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.21530117, 0.        , 0.21530117, ..., 0.        , 0.        ,
        0.        ],
       [0.11675968, 0.11675968, 0.23351936, ..., 0.        , 0.        ,
        0.        ],
       [0.48753433, 0.        , 0.19501373, ..., 0.        , 0.        ,
        0.        ]])

In [76]:
X_Test = preprocessing.normalize(X_Test)
X_Test

array([[0.68020982, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.55168744, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.37031975, 0.        , 0.24687984, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.22699745, 0.11349872, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.11838475, 0.11838475, 0.11838475, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.13141678,
        0.        ]])

#Applying Machine learning Models

**Gaussian Naive Bayes**

In [77]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_Train,Y_Train) #training the model

GaussianNB()

In [78]:
y_pred_test = gnb.predict(X_Test)
y_pred_test

array(['H', 'C', 'H', ..., 'C', 'C', 'C'], dtype='<U1')

**Decision Tree**

In [79]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_Train,Y_Train)
y_pred2 = dt.predict(X_Test)


**KNeighborsClassifier**

In [80]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3,algorithm='ball_tree')
clf.fit(X_Train,Y_Train) #training model
y_pred3 = clf.predict(X_Test) 


In [81]:
y_pred3

array(['A', 'C', 'A', ..., 'G', 'C', 'C'], dtype=object)

In [82]:
y_pred3=pd.DataFrame(y_pred3)
y_pred3 #predicted label

0
0     A
1     C
2     A
3     B
4     C
...  ..
1611  A
1612  C
1613  G
1614  C
1615  C

[1616 rows x 1 columns]

 **SVM**

In [83]:
from sklearn.svm import SVC
svc1 = SVC(C=50,kernel='rbf',gamma=1)     
svc1.fit(X_Train,Y_Train) # training model
y_pred4 = svc1.predict(X_Test)


In [84]:
y_pred4=pd.DataFrame(y_pred4)

In [85]:
y_pred4 #predicted label

0
0     A
1     C
2     C
3     C
4     C
...  ..
1611  A
1612  C
1613  G
1614  C
1615  A

[1616 rows x 1 columns]

**OneVsRestClassifier**

In [ ]:

from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
clf = OneVsRestClassifier(SVC()).fit(X_Train,Y_Train)
y_pred5=clf.predict(X_Test)

Writing the output file

In [86]:
Test=pd.DataFrame(Test)

In [87]:
Test

0                 1
0     1001  AAAIARAGLRHAGGVA
1     1002  AAATGFVKSIAAATGF
2     1003  AADKVEKVDWRTLYIA
3     1004  AADQDPSCLTIQIESA
4     1005  AAEKTKQGAKEGVVAA
...    ...               ...
1611  2612  YYCPLTEEAPPYYCPL
1612  2613  YYFYQQIYPRHGEQFY
1613  2614  YYILCYARHNAPFLYY
1614  2615  YYKAFKITYCKGLDIY
1615  2616  YYWHTGYISLTGKKYT

[1616 rows x 2 columns]

In [88]:
SubmissionCC=pd.concat((Test[0], y_pred4), axis=1, keys=['ID', 'Lable'])

In [89]:
SubmissionCC 

ID Lable
         0     0
0     1001     A
1     1002     C
2     1003     C
3     1004     C
4     1005     C
...    ...   ...
1611  2612     A
1612  2613     C
1613  2614     G
1614  2615     C
1615  2616     A

[1616 rows x 2 columns]

In [90]:
SubmissionCC.to_csv('Fianl_submission.csv')
